puts "The students of my cohort at Makers Academy"
puts "------------"
puts "Mario Gintili"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles de Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhail"
puts "Sarah Young"
puts "Khushkaren Singh"
puts "Rick Brundstedt"
puts "Manjit Singh"
puts "Alex Gaudiosi"
puts "Ross Hepburn"
puts "Natascia Marchese"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine"

print "Overall, we have "
print 9
puts " great students"

print "line1\nline2\nline3" #has to be in double quotes!
