# first, we print the list of students
puts "The students of my cohort at Makers Academy"
puts "------------"
puts "Mario Gintili"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles de Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhail"
puts "Sarah Young"
puts "Khushkaren Singh"
puts "Rick Brundstedt"
puts "Manjit Singh"
puts "Alex Gaudiosi"
puts "Ross Hepburn"
puts "Natascia Marchese"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine"
# finally, we print the total
print "Overall, we have "
print 22
puts " great students"
# it's important that print() doesn't add new line characters